HALL_GAMLE_SCENE = "Gamle scene"
HALL_HOVEDSCENEN = "Hovedscenen"

TEATERSTYKKE_STORST_AV_ALT = "Størst av alt er kjærligheten"
TEATERSTYKKE_KONGSENMNENE = "Kongsemnene"

SECTION_GAMLE_SCENE_PARKETT = "Parkett"
SECTION_GAMLE_SCENE_BALKONG = "Balkong"
SECTION_GAMLE_SCENE_GALLERI = "Galleri"
SECTION_HOVEDSCENEN_PARKETT = "Parkett"
SECTION_HOVEDSCENEN_GALLERI = "Galleri"

DEFAULT_DB = "teater.db"
DEFAULT_SEASON_ID = 1
DEFAULT_CUSTOMER_GROUP = "Ordinær"

ORDNIAER = "Ordinær"
BARN = "Barn"
STUDENT = "Student"
GRUPPE_10 = "Gruppe 10"
GRUPPE_HONNOR = "Gruppe honnør"
HONNOR = "Honnør"


ADMIN_PHONE_NUMBER = 55555555

NO_ROWS_PARKETT_HOVEDSCENEN = 18
NO_ROWS_GALLERI_HOVEDSCENEN = 45
NO_ROWS_GALLERI_GAMLE_SCENE = 3
NO_ROWS_BALKONG_GAMLE_SCENE = 4
NO_ROWS_PARKETT_GAMLE_SCENE = 10

HOVEDSCENEN_PARKETT_SECTION_ID = 1
HOVEDSCENEN_GALLERI_SECTION_ID = 2
GAMLE_SCENE_PARKETT_SECTION_ID = 3
GAMLE_SCENE_BALKONG_SECTION_ID = 4
GAMLE_SCENE_GALLERI_SECTION_ID = 5

NO_SEATS_GAMLE_SCENE_PARKETT = {1: 18, 2: 16, 3: 17, 4: 18, 5: 18, 6: 17, 7: 18, 8: 17, 9: 17, 10: 14}

NO_SEATS_GAMLE_SCENE_BALKONG = {1: 28, 2: 27, 3: 22, 4: 17}

NO_SEATS_GAMLE_SCENE_GALLERI = {1: 33, 2: 18, 3: 17}

HOVEDSCENEN_UNAVAILABLE_SEATS = [467, 468, 469, 470, 495, 496, 497, 498]
